### PR TITLE
Replace game list cell animation using UIViewPropertyAnimator

### PR DESCRIPTION
**Pull request by rosierjolie**
This pull request address the TODO comment found in the setHighlighted method of the GameListGameTableViewCell class.

### CODE REVIEW

**Comment by amiantos** [comment]
We might run into a problem here with two property animators firing at the same time. E.g. if you press down and then lift off before the animation fires, technically the first animation is still firing when the other one fires off. Might lead to some visual glitches, though I can't say for sure because I didn't test it... but in theory what you can do is store the currently running animator in a variable, then when the function gets called again you check the `running` property of the animator stored, and if it is running, you could reverse it. if it isn't running, you can run the new one.

the animators also have completion handlers, so (in theory again) when the animation completes it could clear the variable that stores the animator in it. then checking for a running animation could be a simple `if let` maybe... does this make sense?

**Comment by jerryturcios08** [comment]
Could I also declare a class property to hold the animation, and assign the appropriate animation based on the highlighted property? For instance, I can declare the following

```swift
var highlightAnimator: UIViewPropertyAnimator?
```

Then, in the setHighlighted method, I check if the highlighted parameter is true or false. If true, I assign the variable with an instance of UIViewPropertyAnimator where the shadow opacity is set to 0.0. Else, I assign the variable with an instance where the shadow opacity is set to 0.1. Subsequently, the startAnimation method is called after the variable is assigned based on the highlighted condition.

**Comment by amiantos** [comment]
I might not be following. I don't see how that handles cancelling a property animator that's currently running? Might just wanna wire it up and see how it works.

**Comment by jerryturcios08** [comment]
Hello. I spent some time looking over how I was implementing UIViewPropertyAnimator. I gave your suggestions a try, and I was unable to achieve the needed results. Storing the animator in a variable and reversing the animation when it is running shows the cell being highlighted as usual but the app crashes when exiting the game. I also tried implementing the completion handler for the unhighlight animation, but it did not work as expected since the cell unhighlights immediately before the highlight animation completes. I think the best course of actions for implementing the animation using UIViewPropertyAnimator is the code below:

```swift
if highlighted {
    UIViewPropertyAnimator(duration: 0.05, curve: .linear) { [weak self] in
        self?.gameContainerView.layer.shadowOpacity = 0.0
    }
    .startAnimation()
} else {
    UIViewPropertyAnimator(duration: 0.05, curve: .linear) { [weak self] in
        self?.gameContainerView.layer.shadowOpacity = 0.1
    }
    .startAnimation()
}
```

I also think the following code should suffice for the animation without relying on the UIViewPropertyAnimator class:

```swift
if highlighted {
    UIView.animate(withDuration: 0.05) { [weak self] in
        self?.gameContainerView.layer.shadowOpacity = 0.0
    }
} else {
    UIView.animate(withDuration: 0.05) { [weak self] in
        self?.gameContainerView.layer.shadowOpacity = 0.1
    }
}
```

I tested both, and I get similar results to the old code. What do you think?

**Pull request closed without merging**
